---
title: "Notepad"
author: "Ed Jee"
date: "17 January 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(dplyr)
library(ggplot2)
library(purrr)
library(tibble)

y <- rnorm(1000, 10)
x <- 4*y + rnorm(1000, 4)

find_cov <- function(y, x, delta){
  estimated_cov <- cov(log(y + delta), x)
  df <- tibble(cov = estimated_cov, delta = delta)
  return(df)
}

covs <- seq(from = 0, to = 100, by = 10) %>% 
  map_dfr(~find_cov(y = y, x = x, delta = .))

covs %>% 
  ggplot(aes(x = delta, y = cov)) +
  geom_point()
```


## Thoughts



```{r}
library(dplyr)
library(ggplot2)
library(extraDistr)
library(purrr)

N <- 10000
pi_j <- rhnorm(N)
pi_bar <- mean(pi_j)


create_pi_bar_hn_draw <- function(N = 10000, sigma = 1){
  pi_j <- rhnorm(N, sigma = sigma)
  pi_bar <- mean(pi_j)
  return(pi_bar)
}


pi_bar_hn_draws <- 1:1000 %>% 
  map(~(create_pi_bar_hn_draw())) %>% unlist()

sim_df_hn <- tibble(pi_bar_hn_draws)
ggplot(sim_df_hn, aes(x = pi_bar_hn_draws)) +
  geom_histogram()
```

```{r}
shapiro.test(pi_bar_hn_draws)
cbind(mean(pi_bar_hn_draws),
          sqrt(2)/sqrt(pi))
cbind((1- 2/pi), var(pi_bar_hn_draws)*N)
```



Now half uniform
```{r}

create_pi_bar_hu_draw <- function(N = 10000, max = 100){
  pi_j <- runif(N, min = 0, max = max)
  pi_bar <- mean(pi_j)
  return(pi_bar)
}

pi_bar_hu_draws <- 1:1000 %>% 
  map(~(create_pi_bar_hu_draw())) %>% unlist()
sim_df_hu <- tibble(pi_bar_hu_draws)

ggplot(sim_df_hu,aes(x = pi_bar_hu_draws)) +
  geom_histogram()


```

```{r}
shapiro.test(pi_bar_hu_draws)
```



```{r}

```

