---
title: "LATE"
author: "Ed Jee"
date: "29 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
N <- 10000
z <- rnorm(N)
confounder <-  rnorm(N) 
x <- 2 + 4*z + 10*confounder + rnorm(N) 
y <-  10 + 5*x + 7*confounder + rnorm(N)


lm(y ~ x)
```


Controlling for confounder:
```{r}
lm(y ~ x + confounder)
```

IV

```{r}
library(AER)
ivreg(y ~ x | z)
```



```{r}
library(tibble)
library(broom)
library(dplyr)
library(purrr)
create_fake_data <- function(dummy_arg, N = 10000){
  N <- 10000
  z <- rnorm(N)
  confounder <-  rnorm(N) 
  x <- 2 + 4*z + 10*confounder + rnorm(N) 
  y <-  10 + 5*x + 7*confounder + rnorm(N)
  df <- tibble("y" = y,
               "x" = x,
               "confounder" = confounder,
               "z" = z)
  return(df)
}

find_estimates <- function(dataset){
  coefs_long <- tidy(lm(y ~ x + confounder, data = dataset)) %>% 
    mutate(model = "OLS")
  coefs_IV <- tidy(ivreg(y ~ x | z, data = dataset)) %>% 
    mutate(model = "IV")
  return(bind_rows(coefs_long, coefs_IV))
}

data_draws <- 1:1000 %>% 
  imap_dfr(~create_fake_data(N = 100000) %>% 
  find_estimates() %>% 
    mutate(draw = .y))



```


plotting

```{r}
library(ggplot2)
library(ggridges)
data_draws %>% 
  filter(term == "x") %>% 
  ggplot(aes(x = estimate, y = model, fill = model)) +
  geom_density_ridges() +
  theme_ridges()
```

