---
title: "sim data"
author: "Ed Jee"
date: "15 January 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(dplyr)
library(ggplot2)

create_sim_data <- function(N = 1000,
                            prop_defier = 0.2,
                            beta_defier = -5,
                            beta_complier = 5,
                            intercept_both = 10,
                            sd_both = 5){
  N_defier <- floor(prop_defier*N)
  N_complier <- N - N_defier
  x <- rnorm(N, mean = 10, sd = 10)
  y_defier <- intercept_both + x[1:N_defier]*beta_defier + rnorm(N_defier, mean = 0, sd = sd_both)
  y_complier <- intercept_both + x[(N_defier+1):N]*beta_complier + rnorm(N_complier, mean = 0, sd = sd_both)
  y <- c(y_defier,
         y_complier)
  sim_df <- tibble(x, y)
  return(sim_df)
}
sim_df <- create_sim_data()
```



```{r}
ggplot(sim_df, aes(x = x, y = y)) +
  geom_point()
```



```{r}
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

Need to pick a scale parameter for the half normal
```{r}
library(extraDistr)
hn_df <- tibble(x = rhnorm(1000, sigma = 50))
ggplot(hn_df,
       aes(x = x)) +
  geom_histogram()
```


Using the fact that:
$$
\pi_j \sim N^+(\sigma) \\
\bar{\pi} = \frac{1}{n}\sum^n_{j=0} \pi_j \\
\bar{\pi} \sim N(\frac{\sigma\sqrt2}{\sqrt{\pi}}, \frac{\sigma^2}{n}(1 - \frac{2}{\pi})) ; \   \text{as} \ n \rightarrow \infty

$$

Therefore prior on $\bar{\pi}$ is normal with mean $\frac{50 \sqrt{2}}{\sqrt{\pi}}$ and variance $\frac{50^2}{1000}(1 - \frac{2}{\pi})$
```{r}
library(rstanarm)
mu_0 <- 50*sqrt(2)/sqrt(pi)
var_0 <- (50^2)/1000 * (1-2/pi)
restricted_model <- stan_glm(data = sim_df,
                      y ~ x,
                      prior = normal(mu_0, sqrt(var_0), autoscale = FALSE))
unrestricted_model <- stan_glm(data = sim_df,
                               y ~ x,
                               prior = normal(0, 50, autoscale = FALSE))

```



```{r}
loo_restricted <- loo(restricted_model)
loo_unrestricted <- loo(unrestricted_model)

```



If positive elpd we reject H_0 i.e there is some evidence of defiers

```{r}
compare_models(loo_restricted, loo_unrestricted)
```


## Again but with no defiers


```{r}
no_defiers <- create_sim_data(prop_defier = 0)
ggplot(no_defiers, aes(x = x, y = y)) +
  geom_point()
```



```{r}
restricted_model <- stan_glm(data = no_defiers,
                      y ~ x,
                      prior = normal(mu_0, sqrt(var_0), autoscale = FALSE))
unrestricted_model <- stan_glm(data = no_defiers,
                               y ~ x,
                               prior = normal(0, 50, autoscale = FALSE))

loo_restricted <- loo(restricted_model)
loo_unrestricted <- loo(unrestricted_model)
compare_models(loo_restricted, loo_unrestricted)

```

