---
title: "non neg"
author: "Ed Jee"
date: "15 January 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)

N <- 1000
pi_i <- runif(N, 0, 1)
gamma_i <- rnorm(N)
Z_i <- rnorm(N)


X_i <- gamma_i + pi_i*Z_i + rnorm(N)*50
sim_df <- tibble(pi_i, gamma_i, Z_i, X_i)
```

```{r}
ggplot(sim_df, aes(x = Z_i, y = X_i)) +
  geom_point()
```


```{r}
pi_estim <- lm(X_i ~ Z_i, data = sim_df)
pi_estim
```

```{r}
library(broom)
library(modelr)
library(purrr)
library(tidyr)

boot_df <- bootstrap(sim_df, 100)


boot_models <- boot_df %>% 
    mutate(model = map(strap, ~(lm(X_i ~ Z_i, data = .))),
           pi_ave = map(strap, ~mean(pi_i)),
           coef_info = map(model, tidy))

boot_coefs <- boot_models %>% 
  unnest(coef_info)
boot_pi_ave <- boot_models %>% 
  unnest(pi_ave)
```


```{r}
library(ggridges)


boot_coefs %>%
  filter(term == "Z_i") %>% 
  ggplot(aes(x = estimate)) +
  geom_histogram()
```

```{r}
boot_coefs %>%
  filter(term == "Z_i") %>% 
  arrange(estimate)
```



```{r}
boot_df %>% 
  mutate(pi_first = map(strap, head))
```


```{r}
boot_df$strap[[1]]

sim_df %>% head()
```



## Bates distribution
```{r}

x <- 1:1000 %>% 
  map(~mean(runif(10, 0, 1))) %>% 
  unlist()

y <- 1:1000 %>% 
  map(~mean(runif(2, 0, 1))) %>% 
  unlist()
x_df <- tibble(x, y)
ggplot(x_df, aes(x = x)) +
  geom_histogram(alpha =0.2) +
  geom_histogram(aes(x = y), fill = "red", alpha = 0.2)
```





```{r}
create_bates_draw <- function(a, b, n){
  sgn_bit <- ((x-a)/(b-a) - )
}
```



