---
title: "LATE"
author: "Ed Jee"
date: "29 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
N <- 10000
z <- rnorm(N)
confounder <-  rnorm(N) 
x <- 2 + 4*z + 10*confounder + rnorm(N) 
y <-  10 + 5*x + 7*confounder + rnorm(N)


lm(y ~ x)
```


Controlling for confounder:
```{r}
lm(y ~ x + confounder)
```

IV

```{r}
library(AER)
ivreg(y ~ x | z)
```



```{r}
library(modelr)
library(tidyr)
library(tibble)
library(broom)
library(dplyr)
library(purrr)
create_fake_data <- function(dummy_arg, N = 10000){
  N <- 10000
  z <- rnorm(N)
  confounder <-  rnorm(N) 
  x <- 2 + 4*z + 10*confounder + rnorm(N) 
  y <-  10 + 5*x + 7*confounder + rnorm(N)
  df <- tibble("y" = y,
               "x" = x,
               "confounder" = confounder,
               "z" = z)
  return(df)
}

find_estimates <- function(dataset){
  coefs_long <- tidy(lm(y ~ x + confounder, data = dataset)) %>% 
    mutate(model = "OLS")
  coefs_IV <- tidy(ivreg(y ~ x | z, data = dataset)) %>% 
    mutate(model = "IV")
  coefs_first_stage <- tidy(lm(x ~ z, data = dataset)) %>% 
    mutate(model = "First Stage")
  return(bind_rows(coefs_long, coefs_IV, coefs_first_stage))
}

data_draws <- 1:1000 %>% 
  imap_dfr(~create_fake_data(N = 100000) %>% 
  find_estimates() %>% 
    mutate(draw = .y))



```


plotting

```{r}
library(ggplot2)
library(ggridges)
data_draws %>% 
  filter(term == "x") %>% 
  ggplot(aes(x = estimate, y = model, fill = model)) +
  geom_density_ridges() +
  theme_ridges()
```


```{r}
data_draws %>% 
  filter(term == "z") %>% 
  ggplot(aes(x = estimate)) +
  geom_histogram()
```



####



```{r}
df <- create_fake_data()

ivreg(y ~ x | z, data = df)
```


```{r}
boots <- bootstrap(df, 1000)
fit_iv_on_bs <- function(split){
  model <- ivreg(y ~ x | z, data = split)
  return(model)
}

boot_models <- boots %>% 
  mutate(model = map(strap, fit_iv_on_bs),
         coef_info = map(model, tidy))
boot_coefs <- boot_models %>% 
  unnest(coef_info)
```



plots
```{r}
library(ggridges)
boot_coefs %>% 
  ggplot(aes(x = estimate, y = term, fill = term)) +
  geom_density_ridges() +
  theme_ridges() 
```

fitting first stage

```{r}

fit_first_stage_on_bs <- function(splits){
  model <- lm(x ~ z, data = splits)
  return(model)
}

boot_models <- boots %>% 
  mutate(model = map(strap, fit_first_stage_on_bs),
         coef_info = map(model, tidy))
boot_coefs <- boot_models %>% 
  unnest(coef_info)

boot_coefs %>% 
  filter(term == "z") %>% 
  ggplot(aes(x = estimate)) +
  geom_histogram()
```


## First Stage different for two groups

```{r}
create_fake_data_LATE <- function(dummy_arg, N = 10000, group_prop = 0.5, pi_a = 4, pi_b = 4){
  z <- rnorm(N)
  confounder <-  rnorm(N) 
  indicator <- rbernoulli(N, p = group_prop)
  x <- 2 + indicator*pi_a*z + (1 - indicator)*pi_b*z + 10*confounder + rnorm(N, sd = 20) 
  y <-  10 + 5*x + 7*confounder + rnorm(N)
  df <- tibble("y" = y,
               "x" = x,
               "confounder" = confounder,
               "z" = z)
  return(df)
}

LATE_DF_mono <- create_fake_data_LATE(group_prop = 0.5, pi_a = 0.1, pi_b = 0.5)
boot_mono <- bootstrap(LATE_DF_mono, 1000)

boot_models <- boot_mono %>% 
  mutate(model = map(strap, fit_first_stage_on_bs),
         coef_info = map(model, tidy))
boot_coefs <- boot_models %>% 
  unnest(coef_info)

boot_coefs %>% 
  filter(term == "z") %>% 
  ggplot(aes(x = estimate)) +
  geom_histogram() +
  geom_vline(xintercept = 0)

```

